# This is a basic workflow to help you get started with Actions

name: test CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ dev ]
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs
  #build the app
  # buildBeforeTest:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - name: Checks-out Repo
  #       uses: actions/checkout@v2
  #     - name: Setup node
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: '14.x'

  #     # install applicaion dependencies
  #     - name: Install Dependencies & angular
  #       run: |
  #         npm install
  #         npm install -g @angular/cli 

  #     # run a set of build commands
  #     - name: build
  #       run: ng build

  # test our application       
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # test only if build success
    # needs: [buildBeforeTest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '14.x'

      # install applicaion dependencies
      - name: Install Dependencies & angular
        run: |
          npm install
          npm install -g @angular/cli 

      # run a set of test commands
      - name: test
        run: echo 'this is a test'
